spring:
  application:
    name: spring-boot-cache
  datasource:
    url: jdbc:h2:file:./data/peopledb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: people
    username: sa
    password:
    generate-unique-name: false
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
#  cache:
#    type: none  #If we want to disable caching in any environment then use spring.cache.type property.
